set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sw[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property PACKAGE_PIN J1 [get_ports {led[0]}]
set_property PACKAGE_PIN H3 [get_ports {led[1]}]
set_property PACKAGE_PIN M6 [get_ports {sw[7]}]
set_property PACKAGE_PIN P8 [get_ports {sw[6]}]
set_property PACKAGE_PIN T7 [get_ports {sw[5]}]
set_property PACKAGE_PIN N6 [get_ports {sw[4]}]
set_property PACKAGE_PIN R8 [get_ports {sw[3]}]
set_property PACKAGE_PIN T8 [get_ports {sw[2]}]
set_property PACKAGE_PIN P4 [get_ports {sw[1]}]
set_property PACKAGE_PIN P1 [get_ports {sw[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports buzzer]
set_property PACKAGE_PIN K12 [get_ports buzzer]
set_property PACKAGE_PIN N11 [get_ports clk]
set_property PACKAGE_PIN J3 [get_ports {led[2]}]

set_property PACKAGE_PIN R1 [get_ports {lcd_data[3]}]
set_property PACKAGE_PIN R3 [get_ports {lcd_data[2]}]
set_property PACKAGE_PIN T2 [get_ports {lcd_data[1]}]
set_property PACKAGE_PIN T4 [get_ports {lcd_data[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[0]}]


set_property PACKAGE_PIN P5 [get_ports rs]
set_property PACKAGE_PIN T3 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports en]
set_property IOSTANDARD LVCMOS33 [get_ports rs]



set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {lcd_data[4]}]
set_property PACKAGE_PIN P3 [get_ports {lcd_data[7]}]
set_property PACKAGE_PIN M5 [get_ports {lcd_data[6]}]
set_property PACKAGE_PIN N4 [get_ports {lcd_data[5]}]
set_property PACKAGE_PIN R2 [get_ports {lcd_data[4]}]
